General build script cleanup.
Former-commit-id: ee67a95807207f9e38a89db248741dcca4fe4a53

diff --git a/Deploy/Master/create-python-bundle b/Deploy/Master/create-python-bundle
--- a/Deploy/Master/create-python-bundle
+++ b/Deploy/Master/create-python-bundle
@@ -4,12 +4,15 @@ set -ex
 
 CODE_ARTIFACT_HOST=datalabs-644454719059.d.codeartifact.us-east-1.amazonaws.com
 
+ENVIRONMENT=
 PROJECT=
 PACKAGE=
+VERSION=
 EXTRA_FILES=
 NO_SOURCES=
 NO_VERIFY_SSL=
 TRUSTED_HOSTS=
+USE_PACKAGE=False
 
 
 
@@ -29,6 +32,11 @@ process_arguments() {
             print_usage
             exit 0
             ;;
+        -e|--environment)
+            ENVIRONMENT=$2
+            shift
+            shift
+            ;;
         -f|--file)
             EXTRA_FILES+="-f $2 "
             shift
@@ -41,6 +49,12 @@ process_arguments() {
             ;;
         -P|--package)
             PACKAGE=$2
+            USE_PACKAGE=True
+            shift
+            shift
+            ;;
+        -V|--version)
+            VERSION=$2
             shift
             shift
             ;;
@@ -60,15 +74,18 @@ process_arguments() {
     if [[ "$PROJECT" == "" ]]; then
         echo "Error: missing project argument"
         exit 1
+    elif [[ "$USE_PACKAGE" == "True" && "$VERSION" == "" ]]; then
+        echo "Error: missing package version"
+        exit 1
     fi
 }
 
 
 install_dependencies() {
-    if [[ "$PACKAGE" != "" ]]; then
+    if [[ "$USE_PACKAGE" == "True" ]]; then
         NO_SOURCES=--no-sources
 
-        echo "$PACKAGE" > requirements.txt
+        echo "$PACKAGE==$VERSION" > requirements.txt
 
         aws ${NO_VERIFY_SSL} --profile default codeartifact login --tool pip --domain datalabs --repository datalabs-sbx
     else
@@ -95,7 +112,8 @@ print_usage() {
     echo "  -h, --help                            print this usage text"
     echo "  -f, --file <file>                     include <file> in the bundle"
     echo "  -p, --project <project>               project path relative to Build/"
-    echo "  -P, --package <package==version>      use pre-packaged code instead of sources"
+    echo "  -P, --package <package>               CodeArtifact package name to use instead of sources"
+    echo "  -V, --version <version>               CodeArtifact package version"
     echo "  --no-verify-ssl                       disable verification of server SSL certificate"
 }
 
diff --git a/Deploy/Master/deploy-container-image b/Deploy/Master/deploy-container-image
--- a/Deploy/Master/deploy-container-image
+++ b/Deploy/Master/deploy-container-image
@@ -11,9 +11,8 @@ AWS_DEFAULT_REGION=us-east-1
 REPOSITORY=
 ENVIRONMENT=
 PROJECT=
-RUNTIME=
-PACKAGE_NAME=
-PACKAGE_VERSION=
+PACKAGE=
+VERSION=
 DEPLOYED_VERSION=
 
 
@@ -22,12 +21,7 @@ main() {
 
     get_deployed_version
 
-    if [[ "$RUNTIME" == "Python" ]]; then
-        determine_python_package
-    else
-        echo "Unsupported runtime: $RUNTIME"
-        exit 1
-    fi
+    determine_package_info
 
     if [[ "$DEPLOYED_VERSION" != "$RELEASE_VERSION" ]]; then
         build_container_image
@@ -93,21 +87,17 @@ get_deployed_version() {
 }
 
 
-determine_python_package() {
+determine_package_info() {
     source Build/${PROJECT}/.ci/release.sh $ENVIRONMENT
-    version="$RELEASE_VERSION"
 
-    if [[ "$RELEASE_VERSION" == "dev" ]]; then
-        version=$(
-            aws --profile default codeartifact list-package-versions \
-                --domain datalabs --repository datalabs-sbx --package $RELEASE_NAME \
-                --format pypi --sort-by PUBLISHED_TIME \
-                | grep -m 1 -e '"version": ' | sed 's/..*: "//' | sed 's/",//'
-        )
+    if [[ "$RELEASE_TYPE" == "Python" ]]; then
+        determine_python_package_info
+    elif [[ "$RELEASE_TYPE" == "Java" ]]; then
+        determine_java_package_info
+    else
+        echo "Error: invalid runtime "'"'"$RELEASE_TYPE"'"'""
+        exit 1
     fi
-
-    PACKAGE_NAME=${RELEASE_NAME}
-    PACKAGE_VERSION=${version}
 }
 
 
@@ -141,6 +131,40 @@ print_usage() {
     echo "  -p, --project <project>               project path relative to Build/"
     echo "  -P, --package                         use the latest pre-packaged component instead of sources"
     echo "  -b, --bundle <bundle>                 name of the uploaded bundle file in S3"
+}
+
+
+determine_python_package_info() {
+    local version=$RELEASE_VERSION
+
+    if [[ "$VERSION" == "dev" ]]; then
+        VERSION=$(
+            aws --profile default codeartifact list-package-versions \
+                --domain datalabs --repository datalabs-sbx --package $PACKAGE \
+                --format pypi --sort-by PUBLISHED_TIME | jq -r '.versions[0].version'
+        )
+    fi
+
+    PACKAGE="--package $RELEASE_NAME"
+    VERSION="--version $RELEASE_VERSION"
+}
+
+
+determine_java_package_info() {
+    source Build/${PROJECT}/.ci/release.sh ${ENVIRONMENT}
+    local package=${RELEASE_NAME#datalabs-}
+    local version=$RELEASE_VERSION
+
+    if [[ "$VERSION" == "dev" ]]; then
+        VERSION=$(
+            aws --profile default codeartifact list-package-versions \
+                --domain datalabs --repository datalabs-sbx --namespace org.ama-assn.datalabs --package $PACKAGE \
+                --format maven --sort-by PUBLISHED_TIME | jq -r '.versions[0].version'
+        )
+    fi
+
+    PACKAGE="--package $package"
+    VERSION="--version $version"
 }
 
 
diff --git a/Deploy/Master/deploy-lambda-function b/Deploy/Master/deploy-lambda-function
--- a/Deploy/Master/deploy-lambda-function
+++ b/Deploy/Master/deploy-lambda-function
@@ -18,9 +18,10 @@ PROJECT=
 BUNDLE=
 RUNTIME=
 EXTRA_FILES=
-PACKAGE=
-METADATA=
 DEPLOYED_VERSION=
+METADATA=
+PACKAGE=
+VERSION=
 
 
 main() {
@@ -29,9 +30,7 @@ main() {
     if [[ "$USE_PACKAGE" == "True" ]]; then
         get_deployed_version
 
-        if [[ "$RUNTIME" == "Python" ]]; then
-            determine_python_package
-        fi
+        determine_package_info
     fi
 
     if [[ "$USE_PACKAGE" == "False" || "$DEPLOYED_VERSION" != "$RELEASE_VERSION" ]]; then
@@ -84,7 +83,7 @@ process_arguments() {
             shift
             shift
             ;;
-        -P|--use-package)
+        -u|--use-package)
             USE_PACKAGE=True
             shift
             ;;
@@ -136,15 +135,17 @@ create_code_bundle() {
     fi
 
     if [[ "$RUNTIME" == "Python" ]]; then
+        local use_package=
+
         if [[ "$USE_PACKAGE" == "True" ]]; then
-            determine_python_package
+            use_package="--use-package"
         fi
 
-        ${PWD}/Deploy/Master/create-python-bundle --project $PROJECT $PACKAGE $EXTRA_FILES
+        ${PWD}/Deploy/Master/create-python-bundle --project $PROJECT $PACKAGE $VERSION $EXTRA_FILES
     elif [[ "$RUNTIME" == "Java" ]]; then
         cp Build/${PROJECT}/log4j2.xml ./log4j2.xml
 
-        ${PWD}/Deploy/Master/create-java-bundle --project $PROJECT $EXTRA_FILES -f ./log4j2.xml
+        ${PWD}/Deploy/Master/create-java-bundle --project $PROJECT $PACKAGE $VERSION $EXTRA_FILES -f ./log4j2.xml
     else
         echo "Error: invalid runtime "'"'"$RUNTIME"'"'""
         exit 1
@@ -171,8 +172,8 @@ print_usage() {
     echo "  -h, --help                            print this usage text"
     echo "  -e, --environment <environment>       deployment environment (dev, tst, itg, prd)"
     echo "  -p, --project <project>               project path relative to Build/"
-    echo "  -P, --package                         use the latest pre-packaged component instead of sources"
     echo "  -b, --bundle <bundle>                 name of the uploaded bundle file in S3"
+    echo "  -u, --use-package                     use the associated component package instead of sources"
 }
 
 
@@ -202,20 +203,54 @@ install_sqlserver_driver() {
 }
 
 
-determine_python_package() {
+determine_package_info() {
     source Build/${PROJECT}/.ci/release.sh $ENVIRONMENT
-    version="$RELEASE_VERSION"
 
-    if [[ "$RELEASE_VERSION" == "dev" ]]; then
-        version=$(
+    if [[ "$RELEASE_TYPE" == "Python" ]]; then
+        determine_python_package_info
+    elif [[ "$RELEASE_TYPE" == "Java" ]]; then
+        determine_java_package_info
+    else
+        echo "Error: invalid runtime "'"'"$RELEASE_TYPE"'"'""
+        exit 1
+    fi
+
+    RUNTIME=$RELEASE_TYPE
+}
+
+
+determine_python_package_info() {
+    local version=$RELEASE_VERSION
+
+    if [[ "$VERSION" == "dev" ]]; then
+        VERSION=$(
             aws --profile default codeartifact list-package-versions \
-                --domain datalabs --repository datalabs-sbx --package $RELEASE_NAME \
-                --format pypi --sort-by PUBLISHED_TIME \
-                | grep -m 1 -e '"version": ' | sed 's/..*: "//' | sed 's/",//'
+                --domain datalabs --repository datalabs-sbx --package $PACKAGE \
+                --format pypi --sort-by PUBLISHED_TIME | jq -r '.versions[0].version'
         )
     fi
 
-    PACKAGE="--package ${RELEASE_NAME}==${version}"
+    PACKAGE="--package $RELEASE_NAME"
+    VERSION="--version $RELEASE_VERSION"
+    METADATA='--metadata {"package_version":"'${version}'"}'
+}
+
+
+determine_java_package_info() {
+    source Build/${PROJECT}/.ci/release.sh ${ENVIRONMENT}
+    local package=${RELEASE_NAME#datalabs-}
+    local version=$RELEASE_VERSION
+
+    if [[ "$VERSION" == "dev" ]]; then
+        VERSION=$(
+            aws --profile default codeartifact list-package-versions \
+                --domain datalabs --repository datalabs-sbx --namespace org.ama-assn.datalabs --package $PACKAGE \
+                --format maven --sort-by PUBLISHED_TIME | jq -r '.versions[0].version'
+        )
+    fi
+
+    PACKAGE="--package $package"
+    VERSION="--version $version"
     METADATA='--metadata {"package_version":"'${version}'"}'
 }
 
