Advance to prod.
Former-commit-id: 722c9e3033c52b3486b22cb72b5822b6a5f27a84

diff --git a/Deploy/Master/create-python-bundle b/Deploy/Master/create-python-bundle
--- a/Deploy/Master/create-python-bundle
+++ b/Deploy/Master/create-python-bundle
@@ -1,9 +1,11 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 set -ex
 
 PROJECT=
+PACKAGE=
 EXTRA_FILES=
+NO_SOURCES=
 
 
 
@@ -33,6 +35,11 @@ process_arguments() {
             shift
             shift
             ;;
+        -P|--package)
+            PACKAGE=$2
+            shift
+            shift
+            ;;
         *)
             echo "Unexpected argument $1"
             print_usage
@@ -40,12 +47,23 @@ process_arguments() {
             ;;
       esac
     done
+
+    if [[ "$PROJECT" == "" ]]; then
+        echo "Error: missing project argument"
+        exit 1
+    fi
 }
 
 
 install_dependencies() {
     cat Build/Master/requirements.txt | grep pip== > pip-requirements.txt
     pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org -r pip-requirements.txt
+
+    if [[ "$PACKAGE" != "" ]]; then
+        NO_SOURCES=--no-sources
+
+        echo "$PACKAGE" >> Build/${PROJECT}/requirements.txt
+    fi
 
     pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org --target Bundle/ -r Build/${PROJECT}/requirements.txt
 }
@@ -54,7 +72,7 @@ install_dependencies() {
 create_bundle() {
     export PYTHONPATH=${PWD}/Source/Python
 
-    python Script/bundle_python_project.py --in-place --directory Bundle/ ${EXTRA_FILES} ${PROJECT}
+    python Script/bundle_python_project.py --in-place --directory Bundle/ ${EXTRA_FILES} ${NO_SOURCES} ${PROJECT}
 
 }
 
@@ -67,6 +85,7 @@ print_usage() {
     echo "  -h, --help                            print this usage text"
     echo "  -f, --file <file>                     include <file> in the bundle"
     echo "  -p, --project <project>               project path relative to Build/"
+    echo "  -P, --package <package==version>      use pre-packaged code instead of sources"
 }
 
 
