Implement Java bundle creation script.
Former-commit-id: 7a4663c653d073281292129fbbe44d7a3a9e975f

diff --git a/Deploy/Master/create-java-bundle b/Deploy/Master/create-java-bundle
--- a/Deploy/Master/create-java-bundle
+++ b/Deploy/Master/create-java-bundle
@@ -2,15 +2,24 @@
 
 set -ex
 
+ENVIRONMENT=
 PROJECT=
 EXTRA_FILES=
+PACKAGE=
+VERSION=
 
 
 
 main() {
     process_arguments "$@"
 
-    create_bundle
+    create_server_config
+
+    determine_package_info
+
+    download_package_jar
+
+    supplement_jar
 }
 
 
@@ -21,8 +30,13 @@ process_arguments() {
             print_usage
             exit 0
             ;;
+        -e|--environment)
+            ENVIRONMENT=$2
+            shift
+            shift
+            ;;
         -f|--file)
-            EXTRA_FILES+="-f $2 "
+            EXTRA_FILES+="$2 "
             shift
             shift
             ;;
@@ -38,22 +52,96 @@ process_arguments() {
             ;;
       esac
     done
+
+    if [[ "$ENVIRONMENT" == "" ]]; then
+        echo "Missing environment argument."
+        exit 1
+    elif  [[ "$PROJECT" == "" ]]; then
+        echo "Missing project argument."
+        exit 1
+    fi
 }
 
 
-create_bundle() {
-    export PYTHONPATH=${PWD}/Source/Python
+create_server_config() {
+    if [ -e ~/.m2/settings.xml ]; then
+        echo "The file ~/.m2/settings.xml already exists. Aborting..."
 
-    python Script/bundle_java_project.py --use-pom --directory Bundle/ ${EXTRA_FILES} ${PROJECT}
+        exit 1
+    fi
+    export CODEARTIFACT_AUTH_TOKEN=$(
+        aws --profile default codeartifact get-authorization-token --domain datalabs\
+        --query authorizationToken --output text
+    )
+
+    cat > ~/.m2/settings.xml <<EOF
+<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
+          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
+          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
+    <profiles>
+        <profile>
+            <id>default</id>
+            <repositories>
+                <repository>
+                    <id>codeartifact</id>
+                    <url>https://datalabs-644454719059.d.codeartifact.us-east-1.amazonaws.com/maven/datalabs-sbx/</url>
+                </repository>
+            </repositories>
+        </profile>
+    </profiles>
+
+    <activeProfiles>
+        <activeProfile>default</activeProfile>
+    </activeProfiles>
+
+    <servers>
+        <server>
+            <id>codeartifact</id>
+            <username>aws</username>
+            <password>\${env.CODEARTIFACT_AUTH_TOKEN}</password>
+        </server>
+    </servers>
+</settings>
+EOF
+}
+
+
+determine_package_info() {
+    source Build/${PROJECT}/.ci/release.sh ${ENVIRONMENT}
+
+    PACKAGE=${RELEASE_NAME#datalabs-}
+    VERSION=$RELEASE_VERSION
+
+    if [[ "$VERSION" == "dev" ]]; then
+        VERSION=$(
+            aws --profile default codeartifact list-package-versions \
+                --domain datalabs --repository datalabs-sbx --namespace org.ama-assn.datalabs --package $PACKAGE \
+                --format maven --sort-by PUBLISHED_TIME \
+                | jq -r '.versions[0].version'
+        )
+    fi
+}
+
+
+download_package_jar() {
+    mvn dependency:get -Dartifact=org.ama-assn.datalabs:$PACKAGE:$VERSION
+
+    cp ~/.m2/repository/org/ama-assn/datalabs/${PACKAGE}/${VERSION}/${PACKAGE}-${VERSION}.jar ./${PACKAGE}-${VERSION}.jar
+}
+
+
+supplement_jar() {
+    jar uf ./${PACKAGE}-${VERSION}.jar $EXTRA_FILES
 }
 
 
 print_usage() {
-    echo "Usage: deploy-lambda-function [OPTIONS]..."
-    echo "Bundle and upload a code bundle for a Lambda function."
+    echo "Usage: deploy-java-package [OPTIONS]..."
+    echo "Bundle and upload a code bundle for a Java runtime Lambda function."
     echo
     echo "OPTIONS"
     echo "  -h, --help                            print this usage text"
+    echo "  -e, --environment                     deployment environment (dev, tst, itg, prd)"
     echo "  -f, --file <file>                     include <file> in the bundle"
     echo "  -p, --project <project>               project path relative to Build/"
 }
