Fix deploy-lambda-function script.
Former-commit-id: 6c6cc8dcf43d73ff13adaf6ac13cdabe79a11c5f

diff --git a/Deploy/Master/deploy-lambda-function b/Deploy/Master/deploy-lambda-function
--- a/Deploy/Master/deploy-lambda-function
+++ b/Deploy/Master/deploy-lambda-function
@@ -210,30 +210,36 @@ determine_package_info() {
 
 
 determine_python_package_info() {
-    local version=$(get_package_version $RELEASE_NAME)
+    local version=
+    local return_code=0
+
+    if [[ "$RELEASE_VERSION" == "dev" ]]; then
+        version=$(
+            aws --profile default codeartifact list-package-versions \
+                --domain datalabs --repository datalabs-sbx --package $RELEASE_NAME \
+                --format pypi --sort-by PUBLISHED_TIME | jq -r '.versions[0].version'
+        )
+
+        if [[ ${PIPESTATUS[0]} != 0 ]]; then
+            echo "Error: Package ${RELEASE_NAME} does not exist."
+            return_code=${PIPESTATUS[0]}
+        fi
+    fi
 
     PACKAGE="--package $RELEASE_NAME"
     VERSION="--version $version"
     METADATA='--metadata {"package_version":"'${version}'"}'
+
+    return $return_code
 }
 
 
 determine_java_package_info() {
     local package=${RELEASE_NAME#datalabs-}
-    local version=$(get_package_version $package)
-
-    PACKAGE="--package $package"
-    VERSION="--version $version"
-    METADATA='--metadata {"package_version":"'${version}'"}'
-}
-
-
-get_package_version() {
-    local package=$1
-    local version
+    local version=$(get_package_version $package $RELEASE_VERSION)
     local return_code=0
 
-    if [[ "$version" == "dev" ]]; then
+    if [[ "$release_version" == "dev" ]]; then
         version=$(
             aws --profile default codeartifact list-package-versions \
                 --domain datalabs --repository datalabs-sbx --namespace org.ama-assn.datalabs --package $package \
@@ -241,12 +247,15 @@ get_package_version() {
         )
 
         if [[ ${PIPESTATUS[0]} != 0 ]]; then
-            echo "Error: Package does not exist."
+            echo "Error: Package ${package} does not exist."
             return_code=${PIPESTATUS[0]}
         fi
     fi
 
-    echo $version
+    PACKAGE="--package $package"
+    VERSION="--version $version"
+    METADATA='--metadata {"package_version":"'${version}'"}'
+
     return $return_code
 }
 
