Improve virtual env helper scripts with proper argument parsing and checking. Add jinja2 to PoloRankModel dependencies.
Former-commit-id: 83f324c360b1db1ca2f4efc668c6f90783063d94

diff --git a/Script/setup-virtual-environment b/Script/setup-virtual-environment
--- a/Script/setup-virtual-environment
+++ b/Script/setup-virtual-environment
@@ -1,15 +1,43 @@
 #!/bin/bash
 
 
-SCRIPT=`realpath $0`
-SCRIPT_PATH=`dirname $SCRIPT`
-ENVIRONMENT_PATH=${SCRIPT_PATH}/../Environment/$1
-. ${SCRIPT_PATH}/../Source/Bash/datalabs/environment/setup.sh
+SCRIPT_PATH=`realpath $0`
+SCRIPT_BASE_PATH=`dirname $SCRIPT_PATH`
+. ${SCRIPT_BASE_PATH}/../Source/Bash/datalabs/environment/setup.sh
+PROJECT_NAME=
 
 
 main() {
-    setup_python_virtual_environment ${ENVIRONMENT_PATH}
+    process_arguments $*
+
+    setup_python_virtual_environment ${SCRIPT_BASE_PATH}/../Environment/${PROJECT_NAME}
 }
 
 
-main
+process_arguments() {
+    while (( "$#" )); do
+      case "$1" in
+        -h|--help)
+            print_usage
+            exit 0
+            ;;
+        *)
+            PROJECT_NAME=$1
+            shift
+            ;;
+      esac
+    done
+
+    if [[ "$PROJECT_NAME" == "" ]]; then
+        echo "Error: The name of the project to create was not specified."
+        exit 1
+    fi
+}
+
+
+print_usage() {
+    echo "Usage: setup-virtual-environment <project name> [-h|--help]"
+}
+
+
+main $*
